# Generated by Django 5.1.1 on 2024-10-09 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0018_ticket_3_first_name_ticket_3_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ticket_id', models.CharField(max_length=20, unique=True)),
                ('ticket_data', models.JSONField()),
                ('event_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.event')),
            ],
        ),
        migrations.DeleteModel(
            name='ticket_3',
        ),
    ]
