# Generated by Django 5.1.1 on 2024-10-09 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0019_ticket_delete_ticket_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tk_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='my_app.ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='event_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='my_app.event'),
        ),
    ]
