# Generated by Django 5.1.1 on 2024-10-09 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0020_event_tk_id_alter_ticket_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tk_id',
        ),
    ]
