# Generated by Django 5.1.1 on 2024-10-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0023_ticket_uploaded_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='enc_tk_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
