# Generated by Django 5.1.1 on 2024-10-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0024_ticket_enc_tk_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='enc_tk_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
